[package]
name = "rft"
version = "0.1.0"
authors = ["Peter Okelmann <okelmann@in.tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
byteorder = "^1.3.0"
leb128 = "^0.2.0"
itertools = "^0.9.0"